window.QuestionBankData = `id,topicId,question,optionA,optionB,optionC,answer,explanation
101,1,"Kirchhoff's Current Law (KCL) is based on conservation of:","Energy","Charge","Mass","Charge","Charge cannot be accumulated at a node."
102,1,"Kirchhoff's Voltage Law (KVL) is based on conservation of:","Energy","Charge","Power","Energy","Sum of voltage drops/rises in a loop is zero (work done is zero)."
103,1,"Ohm's Law states relation between:","V, I, P","V, I, R","P, I, R","V, I, R","V = IR."
104,1,"Unit of Resistance is:","Siemens","Ohm","Henry","Ohm","Standard unit."
105,1,"Unit of Conductance is:","Ohm","Siemens","Farad","Siemens","Reciprocal of Ohm."
106,1,"Reciprocal of Resistance is:","Inductance","Conductance","Reactance","Conductance","G = 1/R."
107,1,"Ideal voltage source has internal resistance of:","Zero","Infinite","1 Ohm","Zero","Maintains voltage regardless of current."
108,1,"Ideal current source has internal resistance of:","Zero","Infinite","1 MegaOhm","Infinite","Maintains current regardless of voltage."
109,1,"Nodes are points where:","Two or more elements meet","Only two elements meet","Ground exists","Two or more elements meet","Definition of a node."
110,1,"A loop is:","Any open path","Any closed path","A specific mesh","Any closed path","Starting and ending at the same node."
111,1,"A mesh is a loop that:","Contains no other loops","Contains at least one loop","Is very large","Contains no other loops","Property of planar circuits."
112,1,"Thevenin's Theorem reduces a linear circuit to:","Vth in parallel with Rth","Vth in series with Rth","Ith in series with Rth","Vth in series with Rth","Standard Thevenin equivalent."
113,1,"Norton's Theorem reduces a linear circuit to:","In in series with Rn","In in parallel with Rn","Vn in parallel with Rn","In in parallel with Rn","Standard Norton equivalent."
114,1,"Thevenin Resistance Rth is found by:","Shorting voltage sources, opening current sources","Opening voltage sources, shorting current sources","Leaving sources on","Shorting voltage sources, opening current sources","Deactivating independent sources."
115,1,"Superposition Theorem applies to:","Power","Voltage and Current","Non-linear elements","Voltage and Current","Linear responses only. Power is quadratic (non-linear)."
116,1,"Maximum Power Transfer occurs when Load R equals:","Zero","Source R","Infinite","Source R","Impedance matching condition."
117,1,"Efficiency at Maximum Power Transfer is:","100%","50%","75%","50%","Half power dissipated in source, half in load."
118,1,"Source transformation converts V-source to:","I-source in series with R","I-source in parallel with R","V-source in parallel with R","I-source in parallel with R","V=IR relation holds."
119,1,"Two resistors in series have same:","Voltage","Check","Current","Current","Single path for charge flow."
120,1,"Two resistors in parallel have same:","Current","Voltage","Power","Voltage","Connected to same two nodes."
121,1,"Formula for two resistors R1, R2 in parallel:","R1+R2","(R1*R2)/(R1+R2)","1/R1 + 1/R2","(R1*R2)/(R1+R2)","Product over sum."
122,1,"Voltage Division Rule applies to elements in:","Series","Parallel","Mesh","Series","Divides source voltage proportional to resistance."
123,1,"Current Division Rule applies to elements in:","Series","Parallel","Loop","Parallel","Divides source current inversely proportional to resistance."
124,1,"Power is defined as product of:","V and R","V and I","I and R","V and I","P = VI."
125,1,"Resistors dissipate energy as:","Magnetic field","Heat","Electric field","Heat","Lossy component."
126,1,"Linearity requires:","Additivity and Homogeneity","Stability","Causality","Additivity and Homogeneity","Mathematical definition of linear system."
127,1,"Nodal Analysis uses:","KCL","KVL","Ohm's Law only","KCL","Sum of currents at node is zero."
128,1,"Mesh Analysis uses:","KCL","KVL","Power Balance","KVL","Sum of voltages in loop is zero."
129,1,"A Supernode is formed when:","Current source is between non-reference nodes","Voltage source is between non-reference nodes","Resistor is large","Voltage source is between non-reference nodes","Simplifies nodal analysis."
130,1,"A Supermesh is formed when:","Current source is shared by two meshes","Voltage source is shared","No source is shared","Current source is shared by two meshes","Simplifies mesh analysis."
131,1,"Conductance G equals:","R","1/R","R^2","1/R","Inverse of resistance."
132,1,"Power absorbed by resistor:","I^2 * R","I^2 / R","V * R","I^2 * R","Joule's Law."
133,1,"Dependent sources are controlled by:","Time","Another voltage or current","Temperature","Another voltage or current","VCVS, VCCS, CCVS, CCCS."
134,1,"Active elements:","Dissipate energy","Generate energy","Store energy","Generate energy","Sources, Op-Amps (with supply)."
135,1,"Passive elements:","Cannot generate net energy","Have negative resistance","Are voltage sources","Cannot generate net energy","R, L, C."
136,1,"Short circuit implies:","R=0, V=0","R=inf, I=0","R=0, I=0","R=0, V=0","Zero resistance path."
137,1,"Open circuit implies:","R=0, V=0","R=inf, I=0","R=inf, V=0","R=inf, I=0","No current can flow."
138,1,"Ground reference has voltage:","5V","0V","Infinity","0V","Reference point."
139,1,"Millman's Theorem is useful for:","Parallel voltage sources","Series voltage sources","Series current sources","Parallel voltage sources","Finds common voltage across parallel branches."
140,1,"Tellegen's Theorem relates to:","Power conservation","Voltage division","Current division","Power conservation","Sum of power is zero in any circuit."
141,1,"Dual of Voltage is:","Current","Charge","Flux","Current","Duality principle."
142,1,"Dual of Resistance is:","Inductance","Conductance","Capacitance","Conductance","R <-> G."
143,1,"Instantaneous Power p(t) is:","v(t) * i(t)","Vrms * Irms","Vdc * Idc","v(t) * i(t)","Time domain product."
144,1,"Unit of Charge is:","Ampere","Coulomb","Volt","Coulomb","Standard unit."
145,1,"Unit of Energy is:","Watt","Joule","Newton","Joule","Standard unit."
146,1,"Electron flow is opposite to:","Conventional current","Voltage","Power","Conventional current","Historical definition."
147,1,"Specific resistance depends on:","Length","Material","Area","Material","Resistivity is a material property."
148,1,"Conductivity is inverse of:","Resistance","Resistivity","Conductance","Resistivity","Sigma = 1 / Rho."
149,1,"Temperature coefficient of copper is:","Positive","Negative","Zero","Positive","R increases with T."
150,1,"Resistance of a wire is proportional to:","Area","Length","Volume","Length","R = Rho * L / A."
201,2,"Capacitor stores energy in:","Magnetic field","Electric field","Heat","Electric field","Between plates."
202,2,"Inductor stores energy in:","Magnetic field","Electric field","Chemical bonds","Magnetic field","Flux lines."
203,2,"Unit of Capacitance:","Henry","Farad","Ohm","Farad","F."
204,2,"Unit of Inductance:","Henry","Farad","Weber","Henry","H."
205,2,"Voltage across capacitor cannot change:","Slowly","Instantly","At all","Instantly","Requires infinite current."
206,2,"Current through inductor cannot change:","Slowly","Instantly","Linearly","Instantly","Requires infinite voltage."
207,2,"IV relation for Capacitor:","i = C dv/dt","v = C di/dt","v = iR","i = C dv/dt","Derivative of voltage."
208,2,"IV relation for Inductor:","v = L di/dt","i = L dv/dt","v = Li","v = L di/dt","Derivative of current."
209,2,"Capacitors in parallel combine:","Additively (C1+C2)","Inversely (1/C)","Like resistors","Additively (C1+C2)","Increases plate area."
210,2,"Inductors in series combine:","Additively (L1+L2)","Inversely","Like capacitors","Additively (L1+L2)","Like resistors."
211,2,"DC steady state behavior of Capacitor:","Short Circuit","Open Circuit","Resistor","Open Circuit","dv/dt = 0 -> i = 0."
212,2,"DC steady state behavior of Inductor:","Short Circuit","Open Circuit","Source","Short Circuit","di/dt = 0 -> v = 0."
213,2,"Time constant of RC circuit:","L/R","RC","1/RC","RC","Seconds."
214,2,"Time constant of RL circuit:","L/R","RL","R/L","L/R","Seconds."
215,2,"Energy in Capacitor:","1/2 CV^2","1/2 LI^2","CV","1/2 CV^2"," Joules."
216,2,"Energy in Inductor:","1/2 CV^2","1/2 LI^2","LI","1/2 LI^2","Joules."
217,2,"Ideal Capacitor dissipates:","0 Watts","Infinite Watts","Heat","0 Watts","Stores energy, doesn't burn it."
218,2,"Ideal Inductor dissipates:","0 Watts","I^2 R","Heat","0 Watts","Stores energy only."
219,2,"Mutual Inductance M exists between:","Capacitors","Coupled Inductors","Resistors","Coupled Inductors","Transformers."
220,2,"Coefficient of Coupling k is between:","0 and 1","-1 and 1","1 and 100","0 and 1","Fraction of flux linkage."
221,2,"If k=1, coils are:","Loosely coupled","Perfectly coupled","Uncoupled","Perfectly coupled","Maximum linkage."
222,2,"Capacitance depends on:","Voltage","Geometry and Dielectric","Current","Geometry and Dielectric","Physical property."
223,2,"Dielectric constant affects:","Resistance","Capacitance","Inductance","Capacitance","Increases C."
224,2,"Permeability affects:","Resistance","Capacitance","Inductance","Inductance","Core material property."
225,2,"Identify the passive component:","Transistor","Capacitor","Battery","Capacitor","Passive."
226,2,"Current leads Voltage in:","Inductor","Capacitor","Resistor","Capacitor","ICE (Current in Cap leads EMF)."
227,2,"Voltage leads Current in:","Inductor","Capacitor","Resistor","Inductor","ELI (EMF in Inductor leads I)."
228,2,"Reactance of Capacitor Xc:","wL","1/wC","wC","1/wC","Inverse with freq."
229,2,"Reactance of Inductor Xl:","wL","1/wL","w^2 L","wL","Direct with freq."
230,2,"At DC (f=0), Xc is:","Zero","Infinite","One","Infinite","Open circuit."
231,2,"At DC (f=0), Xl is:","Zero","Infinite","One","Zero","Short circuit."
232,2,"At very high freq, Capacitor acts as:","Short Circuit","Open Circuit","Inductor","Short Circuit","Low impedance."
233,2,"At very high freq, Inductor acts as:","Short Circuit","Open Circuit","Capacitor","Open Circuit","High impedance."
234,2,"Dot convention indicates:","Voltage polarity","Current direction","Winding direction","Voltage polarity","Relative polarity of induced voltage."
235,2,"Capacitors block:","AC","DC","Signals","DC","Open circuit to DC."
236,2,"Inductors block (choke):","High frequencies","Low frequencies","DC","High frequencies","High impedance to AC."
237,2,"Variable capacitor is called:","Potentiometer","Varactor/Trimmer","Rheostat","Varactor/Trimmer","Tunable value."
238,2,"Electrolytic capacitors have:","Polarity","No polarity","Infinite life","Polarity","+ and - terminals."
239,2,"Q factor relates to:","Quality/Energy Storage","Quantity","Quickness","Quality/Energy Storage","Stores energy vs lost."
240,2,"Energy density is highest in:","Capacitors","Inductors","Batteries","Batteries","Chemical storage is denser."
241,2,"Supercapacitors bridge gap between:","Capacitors and Batteries","Inductors and Resistors","None","Capacitors and Batteries","High C, fast charge."
242,2,"Stray capacitance occurs:","Between any conductors","Only in capacitors","In vacuum","Between any conductors","Parasitic effect."
243,2,"Self-resonance freq (SRF) is where component becomes:","Resistive","Non-functional","Ideal","Resistive","L and C cancel."
244,2,"Core saturation happens in:","Air core inductors","Iron core inductors","Capacitors","Iron core inductors","Magnetic limit."
245,2,"Leakage current is found in:","Ideal Capacitors","Real Capacitors","Ideal Inductors","Real Capacitors","Imperfection."
246,2,"Equivalent Series Resistance (ESR) affects:","Capacitor efficiency","Inductor color","Voltage rating","Capacitor efficiency","Parasitic R."
247,2,"Ceramic capacitors are good for:","High frequency","High Energy","DC filtering only","High frequency","Low ESL."
248,2,"Ferrite beads are used as:","Inductors/chokes","Capacitors","Resistors","Inductors/chokes","Suppress EMI."
249,2,"Transformer core is laminated to reduce:","Eddy currents","Weight","Cost","Eddy currents","Heat loss."
250,2,"Flux linkage is:","NI","N * phi","B * A","N * phi","Turns times flux."
301,3,"Transient response is due to:","Resistors","Energy storage elements","Sources","Energy storage elements","L and C cannot change state instantly."
302,3,"Steady state implies:","t = 0","t -> infinity","t = tau","t -> infinity","Responses have settled."
303,3,"Time constant tau for RC:","RC","R/C","1/RC","RC","Seconds."
304,3,"Time constant tau for RL:","L/R","R/L","RL","L/R","Seconds."
305,3,"Voltage across C during charging (step input):","Exponential rise","Linear rise","Instant step","Exponential rise","V(1 - e^-t/tau)."
306,3,"Current in L during energizing (step voltage):","Exponential rise","Step","Linear","Exponential rise","Similar to C voltage."
307,3,"At t=0+, an uncharged capacitor acts as:","Short Circuit","Open Circuit","Resistor","Short Circuit","Voltage is 0, so it looks like a short."
308,3,"At t=0+, an energized inductor acts as:","Current Source","Voltage Source","Open Circuit","Current Source","Maintains initial current."
309,3,"After 1 time constant, response reaches:","50%","63.2%","99%","63.2%","1 - 1/e."
310,3,"After 5 time constants, response is:","Finished",">99%","63%",">99%","Considered settled."
311,3,"Natural response is also called:","Forced response","Zero-input response","Steady state","Zero-input response","Due to initial conditions only."
312,3,"Forced response is due to:","Initial energy","Independent sources","Resistors","Independent sources","The input driving function."
313,3,"Complete response is sum of:","Natural + Forced","DC + AC","V + I","Natural + Forced","Superposition."
314,3,"First-order circuits contain:","1 storage element","2 storage elements","0 storage elements","1 storage element","Or equivalent to 1 (e.g. series C's)."
315,3,"Second-order circuits contain:","R and L","L and C","Two R's","L and C","Or two non-combinable same-type elements."
316,3,"Overdamped response has:","Oscillations","Slow non-oscillatory decay","Fast decay","Slow non-oscillatory decay","Two real roots."
317,3,"Underdamped response has:","Oscillations","No oscillations","Step change","Oscillations","Complex roots (ringing)."
318,3,"Critically damped response is:","Fastest non-oscillatory","Slowest","Oscillatory","Fastest non-oscillatory","Borderline case."
319,3,"Damping ratio 'zeta' < 1 implies:","Overdamped","Underdamped","Critically damped","Underdamped","Oscillatory."
320,3,"In series RLC, 'alpha' (neper freq) is:","R/2L","1/sq(LC)","RC","R/2L","Damping factor definition."
321,3,"Resonant frequency 'omega_0' is:","1/sq(LC)","sq(LC)","R/L","1/sq(LC)","Natural freq."
322,3,"If alpha > omega_0, system is:","Overdamped","Underdamped","Resonant","Overdamped","Dominant damping."
323,3,"Unit impulse response is derivative of:","Step response","Ramp response","Sinusoidal response","Step response","d/dt u(t) = delta(t)."
324,3,"Unit step function u(t) is 1 for:","t < 0","t > 0","all t","t > 0","Heaviside function."
325,3,"Switching usually causes:","Transients","Steady state","Nothing","Transients","Change in state."
326,3,"At t=infinity, L behaves as:","Open","Short","Source","Short","DC short."
327,3,"Continuity condition applies to:","Vr and Ir","Vc and Il","Ic and Vl","Vc and Il","Stored energy variables."
328,3,"Energy in tank circuit (LC) osscilates between:","R and L","L and C","Source and Load","L and C","Electric <-> Magnetic."
329,3,"Time constant is measured in:","Seconds","Hertz","Ohms","Seconds","Time unit."
330,3,"In parallel RLC, alpha is:","1/(2RC)","R/2L","RC","1/(2RC)","Parallel damping."
331,3,"Settle time (5%) is approx:","3 tau","5 tau","1 tau","3 tau","Sometimes 3 or 4 depending on def."
332,3,"Source-free RC circuit voltage:","Decays","Grows","Stays constant","Decays","Resistor dissipates energy."
333,3,"Integrating factor method solves:","1st order diff eq","Algebraic eq","3rd order eq","1st order diff eq","Math tool."
334,3,"Particular solution corresponds to:","Forced response","Natural response","Transient","Forced response","Math term."
335,3,"Homogeneous solution corresponds to:","Forced response","Natural response","Steady State","Natural response","Math term."
336,3,"Characteristic equation roots determine:","Stability/Type of response","Amplitude","Initial value","Stability/Type of response","Exponents."
337,3,"If roots are real and equal:","Critically damped","Overdamped","Underdamped","Critically damped","Repeated roots."
338,3,"Mechanical analog of Inductance is:","Friction","Mass","Spring","Mass","Inertia."
339,3,"Mechanical analog of Capacitance is:","Spring (Compliance)","Mass","Damper","Spring (Compliance)","Elasticity."
340,3,"Mechanical analog of Resistance is:","Damper (Friction)","Mass","Spring","Damper (Friction)","Energy loss."
341,3,"Singularity functions include:","Sin, Cos","Step, Impulse, Ramp","Exp, Log","Step, Impulse, Ramp","Discontinuous functions."
342,3,"Impulse function has area:","Zero","One","Infinite","One","Definition of Dirac Delta."
343,3,"Step response of differentiator is:","Impulse","Ramp","Step","Impulse","Derivative of step is impulse."
344,3,"Impulse response of integrator is:","Step","Ramp","Impulse","Step","Integral of impulse is step."
345,3,"Pulse width affects:","Frequency content","Amplitude only","Phase only","Frequency content","Narrow pulse -> wide bandwidth."
346,3,"Duty cycle is:","On time / Period","Off time / Period","Period / On time","On time / Period","Ratio."
347,3,"Square wave contains:","Even harmonics","Odd harmonics","All harmonics","Odd harmonics","Fourier series property."
348,3,"Which circuit acts as Low Pass Filter?","Series RC (Output across C)","Series RC (Output across R)","Series LC","Series RC (Output across C)","Passes DC."
349,3,"Which circuit acts as High Pass Filter?","Series RC (Output across C)","Series RC (Output across R)","Inductor only","Series RC (Output across R)","Blocks DC."
350,3,"Bandwidth relates to:","Rise time","DC level","Voltage source","Rise time","Inverse relationship."
401,4,"Ideal Op-Amp Input Impedance:","0","Infinite","50 Ohm","Infinite","No input current."
402,4,"Ideal Op-Amp Output Impedance:","0","Infinite","1k Ohm","0","Ideal voltage source output."
403,4,"Ideal Op-Amp Open Loop Gain:","1","100","Infinite","Infinite","Huge amplification."
404,4,"Virtual Short concept implies:","V+ = V-","V+ = 0","Inputs are shorted to ground","V+ = V-","Feedback forces inputs equal."
405,4,"Virtual Ground occurs when:","Non-inverting input is grounded","Inverting input is grounded","Output is grounded","Non-inverting input is grounded","V- follows V+ (0V)."
406,4,"Inverting Amplifier Gain:","-Rf/Rin","1 + Rf/Rin","Rf/Rin","-Rf/Rin","Standard formula."
407,4,"Non-Inverting Amplifier Gain:","-Rf/Rin","1 + Rf/Rin","1","1 + Rf/Rin","Standard formula."
408,4,"Voltage Follower Gain:","1","-1","Infinite","1","Buffer."
409,4,"Why use a Voltage Follower?","Impedance matching/Buffering","Amplification","Inversion","Impedance matching/Buffering","High Zin, Low Zout."
410,4,"Summing Amplifier is based on:","KCL at inverting node","KVL at output","Ohm's law only","KCL at inverting node","Currents sum up."
411,4,"Difference Amplifier measures:","V2 - V1","V2 + V1","V1 * V2","V2 - V1","Subtracts inputs."
412,4,"CMRR stands for:","Common Mode Rejection Ratio","Current Mode Ratio","Common Mode Resistance","Common Mode Rejection Ratio","Ability to reject noise."
413,4,"Ideal CMRR is:","0","1","Infinite","Infinite","Rejects common signals perfectly."
414,4,"Slew Rate is limit on:","Rate of change of Vout","Current output","Input voltage","Rate of change of Vout","Speed of response (V/us)."
415,4,"Integrator circuit uses:","C in feedback","L in feedback","R in feedback","C in feedback","Vout = -1/RC integral(Vin)."
416,4,"Differentiator circuit uses:","C in input","C in feedback","L in input","C in input","Vout = -RC dVin/dt."
417,4,"Op-Amp Comparator output is:","Linear","Saturated (Rail to Rail)","Zero","Saturated (Rail to Rail)","Switches between Vcc and Vee."
418,4,"Schmitt Trigger adds:","Hysteresis","Gain","Bandwidth","Hysteresis","Positive feedback."
419,4,"Negative feedback improves:","Stability and Bandwidth","Gain","Noise","Stability and Bandwidth","Trades gain for performance."
420,4,"Positive feedback causes:","Oscillation/Saturation","Stability","Filtering","Oscillation/Saturation","Used in oscillators."
421,4,"Gain-Bandwidth Product (GBP) is:","Constant","Variable","Zero","Constant","For a given op-amp."
422,4,"Input Bias Current is:","Current entering inputs","Current at output","Supply current","Current entering inputs","Non-ideal behavior."
423,4,"Input Offset Voltage causes:","Output error when Vin=0","Gain error","Bandwidth limit","Output error when Vin=0","Internal mismatch."
424,4,"Instrumentation Amplifier has:","High CMRR and Impedance","Low Impedance","Low Gain","High CMRR and Impedance","Precision measurement."
425,4,"Active Filter use:","Op-Amps + RC","L and C only","Transistors only","Op-Amps + RC","Avoids inductors."
426,4,"Butterworth filter characteristic:","Maximally flat passband","Steep roll-off","Ripple in passband","Maximally flat passband","Smooth."
427,4,"Chebyshev filter characteristic:","Ripple in passband","Flat passband","Linear phase","Ripple in passband","Steeper roll-off."
428,4,"Sallen-Key topology is:","Active filter","Oscillator","Amplifier","Active filter","Common 2nd order block."
429,4,"Op-Amp supply rails determine:","Max output swing","Gain","Bandwidth","Max output swing","Cannot exceed Vcc/Vee."
430,4,"Single supply op-amp needs:","Virtual ground biasing","Negative rail","AC only","Virtual ground biasing","Usually at Vcc/2."
431,4,"PSRR stands for:","Power Supply Rejection Ratio","Phase Shift Ratio","Power Source Ratio","Power Supply Rejection Ratio","Immunity to supply ripple."
432,4,"Ground loop causes:","Noise/Hum","Gain increase","Offset","Noise/Hum","Current flow in ground."
433,4,"Decoupling capacitors are placed:","Near power pins","At input","At output","Near power pins","Stabilize supply."
434,4,"Output short circuit protection:","Limits current","Limits voltage","Stops op-amp","Limits current","Safety feature."
435,4,"Thermal shutdown occurs if:","Op-Amp gets too hot","Input is too high","Output is zero","Op-Amp gets too hot","Safety."
436,4,"Transimpedance amplifier converts:","Current to Voltage","Voltage to Current","R to C","Current to Voltage","I-V converter."
437,4,"Transconductance amplifier converts:","Voltage to Current","Current to Voltage","R to L","Voltage to Current","V-I converter (OTA)."
438,4,"Log amplifier uses:","Diode/BJT in feedback","Capacitor","Resistor","Diode/BJT in feedback","Logarithmic IV curve."
439,4,"Precision rectifier overcomes:","Diode voltage drop","Reverse leakage","Speed limit","Diode voltage drop","Ideal diode behavior."
440,4,"Window comparator detects:","If voltage is within range","If voltage is positive","Peak voltage","If voltage is within range","Two limits."
441,4,"Sample and Hold circuit uses:","Switch and Capacitor","Inductor","Resistor","Switch and Capacitor","Stores voltage."
442,4,"Peak detector stores:","Max voltage","Average voltage","RMS voltage","Max voltage","Using diode and C."
443,4,"Zero crossing detector switches when:","Input crosses 0V","Input is max","Output is 0","Input crosses 0V","Phase detection."
444,4,"Relaxation oscillator uses:","RC charging + Hysteresis","LC tank","Crystal","RC charging + Hysteresis","Square wave gen."
445,4,"Wien Bridge oscillator produces:","Sine wave","Square wave","Triangle wave","Sine wave","Audio freq."
446,4,"Phase shift oscillator uses:","RC network","LC tank","Quartz","RC network","180 deg shift."
447,4,"Triangle wave generator integrates:","Square wave","Sine wave","Ramp","Square wave","Linear charge."
448,4,"Multivibrator stable states (Bi-stable):","2","1","0","2","Flip-flop."
449,4,"Monostable multivibrator is a:","One-shot timer","Clock","Memory","One-shot timer","One stable state."
450,4,"Astable multivibrator is a:","Oscillator (Clock)","Timer","Switch","Oscillator (Clock)","No stable states."
501,5,"Laplace transform converts:","Time domain to s-domain","Freq to Time","Time to Discrete","Time domain to s-domain","Differential eqn to Algebra."
502,5,"Variable 's' is:","Complex frequency (sigma + jw)","Real freq","Time","Complex frequency (sigma + jw)","Definition."
503,5,"L{delta(t)} (Impulse) is:","1","1/s","s","1","Flat spectrum."
504,5,"L{u(t)} (Step) is:","1/s","1","1/s^2","1/s","Integration."
505,5,"L{e^-at} is:","1/(s+a)","1/(s-a)","s+a","1/(s+a)","Exponential decay."
506,5,"L{sin(wt)} is:","w / (s^2 + w^2)","s / (s^2 + w^2)","1 / (s^2 + w^2)","w / (s^2 + w^2)","Standard pair."
507,5,"L{cos(wt)} is:","s / (s^2 + w^2)","w / (s^2 + w^2)","s / (s+w)","s / (s^2 + w^2)","Standard pair."
508,5,"L{t} (Ramp) is:","1/s^2","1/s","2/s^3","1/s^2","Integration of step."
509,5,"Differentiation in time L{df/dt} corresponds to:","sF(s) - f(0)","F(s)/s","sF(s)","sF(s) - f(0)","Frequency derivative."
510,5,"Integration in time L{integral f} corresponds to:","F(s)/s","sF(s)","F(s)","F(s)/s","Frequency integration."
511,5,"Final Value Theorem applies if:","Poles are in LHP (stable)","Poles in RHP","Anytime","Poles are in LHP (stable)","System must settle."
512,5,"Initial Value Theorem gives f(0) from:","lim s->inf sF(s)","lim s->0 sF(s)","F(0)","lim s->inf sF(s)","High freq behavior."
513,5,"Shift in time f(t-a)u(t-a) corresponds to:","e^-as F(s)","e^as F(s)","F(s-a)","e^-as F(s)","Time delay."
514,5,"Shift in frequency F(s+a) corresponds to:","e^-at f(t)","f(t-a)","e^at f(t)","e^-at f(t)","Modulation/Damping."
515,5,"Convolution f * g corresponds to:","F(s) * G(s)","F(s) + G(s)","F(s) / G(s)","F(s) * G(s)","Multiplication in s."
516,5,"Transfer Function H(s) is:","Y(s) / X(s)","X(s) / Y(s)","Y(s) * X(s)","Y(s) / X(s)","Output over Input."
517,5,"Region of Convergence (ROC) relates to:","Existence of Transform","Amplitude","Phase","Existence of Transform","Integral convergence."
518,5,"Inverse Laplace is found via:","Partial Fraction Expansion","Differentiation","Integration","Partial Fraction Expansion","Break down into known pairs."
519,5,"Resistor in s-domain:","R","sR","1/sR","R","No frequency dependence."
520,5,"Inductor in s-domain (zero init):","sL","1/sL","L","sL","Impedance."
521,5,"Capacitor in s-domain (zero init):","1/sC","sC","C","1/sC","Impedance."
522,5,"Impulse response h(t) is inverse Laplace of:","Transfer function H(s)","Input X(s)","Output Y(s)","Transfer function H(s)","Input is 1."
523,5,"Stability is determined by:","Poles","Zeros","Gain","Poles","Denominator roots."
524,5,"System is stable if poles are in:","Left Half Plane","Right Half Plane","Imaginary Axis","Left Half Plane","Decaying exponentials."
525,5,"Marginal stability occurs if poles are on:","Imaginary Axis (simple)","Real Axis","RHP","Imaginary Axis (simple)","Oscillatory constant."
526,5,"Zeros of H(s) affect:","Amplitude/Phase","Stability","DC gain only","Amplitude/Phase","Blocks frequencies."
527,5,"DC Gain is found by setting s to:","0","Infinity","1","0","Zero frequency."
528,5,"High frequency gain is s ->:","Infinity","0","1","Infinity","Limit."
529,5,"Order of system is:","Highest power of s in denominator","Number of zeros","Number of inputs","Highest power of s in denominator","Number of states."
530,5,"Proper transfer function has:","Deg(Num) <= Deg(Den)","Deg(Num) > Deg(Den)","No poles","Deg(Num) <= Deg(Den)","Realizable."
531,5,"Step response is integral of:","Impulse response","Ramp response","Input","Impulse response","Accumulation."
532,5,"Pole at origin (1/s) represents:","Integrator","Differentiator","Gain","Integrator","Accumulator."
533,5,"Zero at origin (s) represents:","Differentiator","Integrator","Delay","Differentiator","Slope."
534,5,"Complex conjugate poles result in:","Oscillation","Exponential decay only","Instability","Oscillation","Sinusoidal component."
535,5,"Unilateral Laplace Transform integrates from:","0- to Infinity","-Inf to Inf","0 to T","0- to Infinity","Causal systems."
536,5,"Bilinear transform maps s-plane to:","z-plane","t-domain","w-plane","z-plane","Digital control."
537,5,"Initial energy in L is modeled as:","Current source in parallel","Voltage source in parallel","Resistor","Current source in parallel","With 1/sL impedance."
538,5,"Initial voltage on C is modeled as:","Voltage source in series","Current source in series","Resistor","Voltage source in series","V/s source."
539,5,"Residue theorem is used for:","Inverse Laplace","Forward Laplace","Stability","Inverse Laplace","PFE coefficients."
540,5,"Cascaded blocks H1, H2 total generic:","H1 * H2","H1 + H2","H1 / H2","H1 * H2","Multiplication."
541,5,"Parallel blocks H1, H2 total:","H1 + H2","H1 * H2","H1 - H2","H1 + H2","Summation."
542,5,"Feedback system transfer function:","G / (1 + GH)","G * H","G + H","G / (1 + GH)","Black's formula."
543,5,"Characteristic equation is:","1 + GH = 0","G = 0","H = 0","1 + GH = 0","Determines poles."
544,5,"Routh-Hurwitz criterion checks:","Stability","Accuracy","Speed","Stability","Without solving roots."
545,5,"Root Locus plots movement of:","Poles vs Gain","Zeros vs Time","Response","Poles vs Gain","Design tool."
546,5,"Bode Plot shows:","Magnitude and Phase vs Freq","Pole locations","Time response","Magnitude and Phase vs Freq","Frequency response."
547,5,"Decibel (dB) gain is:","20 log(mag)","10 log(mag)","ln(mag)","20 log(mag)","Voltage gain."
548,5,"Low pass filter pole location:","-w_c","0","+w_c","-w_c","Corner frequency."
549,5,"State space representation uses:","Matrices","Transfer functions only","Graphs","Matrices","ABCD matrices."
550,5,"Laplace of t*f(t):","-dF/ds","F'(s)","sF(s)","-dF/ds","Frequency differentiation."
601,6,"Network function H(s) is ratio of:","Response to Excitation","Excitation to Response","Power to Voltage","Response to Excitation","Output/Input."
602,6,"Driving point impedance is:","V(s)/I(s) at same port","V2/V1","I2/I1","V(s)/I(s) at same port","Input impedance."
603,6,"Transfer impedance is:","V_out / I_in","V_in / I_out","V_out / V_in","V_out / I_in","Transimpedance."
604,6,"Voltage gain function:","V2/V1","I2/I1","V2/I1","V2/V1","Dimensionless."
605,6,"Poles of H(s) determine:","Natural response/Stability","Magnitude only","Zeros","Natural response/Stability","Time domain form."
606,6,"Zeros of H(s) determine:","Frequencies blocked","Stability","Decay rate","Frequencies blocked","Transmission zeros."
607,6,"Reciprocal network implies:","Z12 = Z21","Z11 = Z22","Z11 = 0","Z12 = Z21","Swap input/output."
608,6,"Symmetrical network implies:","Z11 = Z22","Z12 = 0","Z21 = 1","Z11 = Z22","Input/Output ports identical."
609,6,"Z-parameters are:","Impedance parameters","Admittance parameters","Hybrid","Impedance parameters","Open circuit Z."
610,6,"Y-parameters are:","Admittance parameters","Impedance parameters","Transmission","Admittance parameters","Short circuit Y."
611,6,"h-parameters are:","Hybrid parameters","High parameters","Heat parameters","Hybrid parameters","Mixed units."
612,6,"ABCD parameters are:","Transmission parameters","Gain parameters","Scatter","Transmission parameters","Chain parameters."
613,6,"Condition for reciprocity in ABCD:","AD - BC = 1","A = D","B = C","AD - BC = 1","Determinant is 1."
614,6,"Condition for symmetry in ABCD:","A = D","B = C","AD - BC = 0","A = D","Input/Output match."
615,6,"Z11 is measured with:","Port 2 Open","Port 2 Short","Port 1 Short","Port 2 Open","Input impedance open."
616,6,"Y11 is measured with:","Port 2 Short","Port 2 Open","Port 1 Open","Port 2 Short","Input admittance short."
617,6,"h21 represents:","Forward Current Gain","Input Impedance","Output Admittance","Forward Current Gain","Current ratio."
618,6,"g-parameters are inverse of:","h-parameters","z-parameters","y-parameters","h-parameters","Inverse hybrid."
619,6,"T-network is equivalent to:","Y-network (Star)","Pi-network (Delta)","Bridge","Y-network (Star)","Topology."
620,6,"Pi-network is equivalent to:","Delta","Star","Series","Delta","Topology."
621,6,"Interconnection of Z-params in series:","Z_eq = Z_a + Z_b","Z_eq = Z_a * Z_b","Z_eq = Z_a || Z_b","Z_eq = Z_a + Z_b","Matrices add."
622,6,"Interconnection of Y-params in parallel:","Y_eq = Y_a + Y_b","Y_eq = Y_a * Y_b","Inverse","Y_eq = Y_a + Y_b","Matrices add."
623,6,"Cascade connection uses:","ABCD parameters","Z parameters","h parameters","ABCD parameters","Matrix multiplication."
624,6,"Image impedance matches:","Source and Load for symmetry","Only Source","Only Load","Source and Load for symmetry","Iterative impedance."
625,6,"Bartlett's Bisection Theorem finds:","Lattice equivalents","Poles","Gain","Lattice equivalents","Symmetric networks."
626,6,"Ideally, passband attenuation is:","0 dB","3 dB","Infinite","0 dB","No loss."
627,6,"Stopband attenuation should include:","Infinite attenuation","0 dB","Gain","Infinite attenuation","Total block."
628,6,"Cutoff frequency is defined at:","-3 dB power point","-10 dB","0 dB","-3 dB power point","Half power."
629,6,"Quality factor Q of bandpass filter:","Center freq / Bandwidth","Bandwidth / Center freq","Gain / Freq","Center freq / Bandwidth","Selectivity."
630,6,"Sensitivity analysis measures:","Change in H per change in element","Input limit","Noise","Change in H per change in element","Robustness."
631,6,"Hurwitz polynomial has roots in:","LHP only","RHP only","Anywhere","LHP only","Stable denominator."
632,6,"Positive Real Function (PRF) represents:","Passive driving point impedance","Active gain","Unstable system","Passive driving point impedance","Real parts > 0."
633,6,"Bott-Duffin synthesis avoids:","Transformers","Capacitors","Resistors","Transformers","Realization technique."
634,6,"Foster Form I involves:","Partial fraction of Z(s)","Continued fraction","Product","Partial fraction of Z(s)","Series LC tanks."
635,6,"Cauer Form I involves:","Continued fraction expansion","Partial fraction","Sum","Continued fraction expansion","Ladder network."
636,6,"Constant K filter is a:","Prototype filter","Active filter","Digital filter","Prototype filter","Image parameter method."
637,6,"m-derived filter improves:","Rolloff steepness","Passband","Gain","Rolloff steepness","Sharper cutoff."
638,6,"Attenuator is a:","Resistive network to reduce signal","Amplifier","Filter","Resistive network to reduce signal","Fixed loss."
639,6,"Unit of attenuation:","Neper or Decibel","Watt","Henry","Neper or Decibel","Log ratios."
640,6,"Scattering parameters (S-params) used for:","RF/Microwave","DC","Audio","RF/Microwave","Wave reflections."
641,6,"S11 represents:","Input reflection coefficient","Forward gain","Output match","Input reflection coefficient","Return loss."
642,6,"S21 represents:","Forward transmission gain","Reverse isolation","Reflection","Forward transmission gain","Throughput."
643,6,"Conversion Z to Y:","Inverse matrix","Transpose","Identity","Inverse matrix","[Y] = [Z]^-1."
644,6,"Determinant of Z-matrix Delta_Z is:","Z11Z22 - Z12Z21","Z11+Z22","Z11*Z22","Z11Z22 - Z12Z21","Standard det."
645,6,"Input impedance in terms of ABCD:","(A Zl + B) / (C Zl + D)","A Zl","B / D","(A Zl + B) / (C Zl + D)","Transmission eqn."
646,6,"Gyrator is a:","Non-reciprocal device","Resistor","Capacitor","Non-reciprocal device","Simulates inductance."
647,6,"NIC (Negative Impedance Converter) converts:","Z to -Z","R to C","V to I","Z to -Z","Active circuit."
648,6,"All-pass filter affects:","Phase only","Amplitude only","Neither","Phase only","Flat gain."
649,6,"Notch filter rejects:","Specific narrow band","Low freq","High freq","Specific narrow band","Band stop."
650,6,"Equalizer corrects:","Frequency response distortion","DC offset","Power factor","Frequency response distortion","Flattens response."
701,7,"DC stands for:","Direct Current","Digital Current","Dual Current","Direct Current","Constant polarity."
702,7,"AC stands for:","Alternating Current","Active Current","Analog Current","Alternating Current","Changing polarity."
703,7,"Frequency of DC is:","0 Hz","50 Hz","Infinite","0 Hz","No change over time."
704,7,"In an AC system, frequency represents:","Cycles per second","Amplitude variation","Phase shift","Cycles per second","Definition of Hz."
705,7,"Period T of a waveform is related to frequency f by:","T = 1/f","T = f","T = 2f","T = 1/f","Inverse relationship."
706,7,"RMS stands for:","Root Mean Square","Real Mean Sum","Rated Max Speed","Root Mean Square","Effective DC value."
707,7,"RMS value of sine wave with peak Vm:","Vm / sqrt(2)","Vm * sqrt(2)","Vm / 2","Vm / sqrt(2)","0.707 * Vm."
708,7,"Average value of full sine wave over one period:","0","Vm","Vm/2","0","Positive cancels negative."
709,7,"Average value of half-wave rectified sine:","Vm / pi","2Vm / pi","0","Vm / pi","DC component."
710,7,"Form factor is ratio of:","RMS to Average","Peak to RMS","RMS to Peak","RMS to Average","Waveform shape metric."
711,7,"Crest factor is ratio of:","Peak to RMS","RMS to Average","Average to Peak","Peak to RMS","Peakiness."
712,7,"Impedance Z is vector sum of:","Resistance and Reactance","R and L","V and I","Resistance and Reactance","Z = R + jX."
713,7,"Real power P unit:","Watt (W)","VAR","VA","Watt (W)","Active power."
714,7,"Reactive power Q unit:","Volt-Ampere Reactive (VAR)","Watt","Joule","Volt-Ampere Reactive (VAR)","Stored/returned power."
715,7,"Apparent power S unit:","Volt-Ampere (VA)","Watt","VAR","Volt-Ampere (VA)","Total power magnitude."
716,7,"Power Factor (PF) is:","P / S (Real/Apparent)","Q / S","S / P","P / S (Real/Apparent)","cos(theta)."
717,7,"PF is also equal to:","cos(impedance angle)","sin(angle)","tan(angle)","cos(impedance angle)","Time shift cosine."
718,7,"For purely resistive load, PF is:","1 (Unity)","0","0.5","1 (Unity)","V and I in phase."
719,7,"For purely inductive load, PF is:","0 Lagging","0 Leading","1","0 Lagging","Current lags voltage."
720,7,"For purely capacitive load, PF is:","0 Leading","0 Lagging","1","0 Leading","Current leads voltage."
721,7,"Resonance occurs when:","Xl = Xc","R = 0","Z = infinity","Xl = Xc","Reactances cancel."
722,7,"At series resonance, Impedance is:","Minimum (R)","Maximum","Zero","Minimum (R)","Series LC short."
723,7,"At parallel resonance, Impedance is:","Maximum","Minimum","Zero","Maximum","Tank circuit open."
724,7,"Phasor representation requires:","Same frequency","Same amplitude","DC","Same frequency","Rotating vectors."
725,7,"Phasor length represents:","RMS or Peak value","Frequency","Phase","RMS or Peak value","Magnitude."
726,7,"Phase angle represents:","Time shift","Frequency shift","Amplitude shift","Time shift","Relative timing."
727,7,"Complex power S is:","V_rms * conj(I_rms)","V * I","P + Q","V_rms * conj(I_rms)","S = P + jQ."
728,7,"Skin effect causes resistance to:","Increase with frequency","Decrease with frequency","Stay constant","Increase with frequency","Current crowds surface."
729,7,"DC can be transformed by:","Chopper/Converter","Transformer","Capacitor","Chopper/Converter","Review DC-DC."
730,7,"Transformers work only with:","AC","DC","Static electricity","AC","Need changing flux."
731,7,"Rectifier converts:","AC to DC","DC to AC","AC to AC","AC to DC","Diode bridge."
732,7,"Inverter converts:","DC to AC","AC to DC","DC to DC","DC to AC","Solar/Battery app."
733,7,"Triac controls:","AC power","DC power","Logic","AC power","Bidirectional switch."
734,7,"Capacitor in DC circuit is:","Open (after charge)","Short","Source","Open (after charge)","Blocks DC."
735,7,"Inductor in DC circuit is:","Short (wire)","Open","Resistor","Short (wire)","Passes DC."
736,7,"Why AC for transmission?","Easy voltage step up/down","Safer","Faster electrons","Easy voltage step up/down","Reduced losses."
737,7,"Corona loss occurs in:","High voltage AC lines","DC low voltage","Batteries","High voltage AC lines","Ionization."
738,7,"Ferranti effect causes:","Receiving end V > Sending end V","Voltage drop","Frequency drop","Receiving end V > Sending end V","Load line capacitance."
739,7,"Power factor correction uses:","Capacitor banks","Inductors","Resistors","Capacitor banks","Offset inductive lag."
740,7,"Joule heating formula:","I^2 R t","V I","C V^2","I^2 R t","Heat energy."
741,7,"Max value of sine is at:","90 degrees","0 degrees","180 degrees","90 degrees","Peak."
742,7,"Derivative of sine is:","Cosine","-Cosine","Sine","Cosine","Inductive voltage."
743,7,"Admittance Y is:","1/Z","1/R","Z^2","1/Z","Inverse impedance."
744,7,"Susceptance B is imaginary part of:","Admittance","Impedance","Power","Admittance","Y = G + jB."
745,7,"Harmonics are multiples of:","Fundamental frequency","DC","Amplitude","Fundamental frequency","Distortion."
746,7,"Total Harmonic Distortion (THD) measures:","Waveform purity","Power","Phase","Waveform purity","Ratio of harmonics."
747,7,"Square wave RMS is:","Peak value","Peak/sq(2)","0","Peak value","Area/Time."
748,7,"Symmetrical components used for:","Unbalanced polyphase","DC","Single phase","Unbalanced polyphase","Fortescue."
749,7,"Kirchhoff laws in AC apply to:","Phasors/Instantaneous values","RMS values only","Amplitudes only","Phasors/Instantaneous values","Vector sum."
750,7,"Bandwidth of RLC circuit depends on:","Resistance","Source V","Time","Resistance","Higher R -> Wider (in parallel), Narrower (in series)."
801,8,"Standard phase shift in 3-phase:","120 degrees","90 degrees","180 degrees","120 degrees","Balanced."
802,8,"Sequence ABC is:","Positive Sequence","Negative Sequence","Zero Sequence","Positive Sequence","Standard rotation."
803,8,"Sequence CBA is:","Negative Sequence","Positive Sequence","Zero Sequence","Negative Sequence","Reverse rotation."
804,8,"Wye (Star) connection symbol:","Y","Delta","Pi","Y","Shape."
805,8,"Delta (Mesh) connection symbol:","Triangle","Y","T","Triangle","Greek Delta."
806,8,"In balanced Y, Line Voltage = ?","sq(3) * Phase Voltage","Phase Voltage","3 * Phase Voltage","sq(3) * Phase Voltage","Vl leads Vp by 30."
807,8,"In balanced Y, Line Current = ?","Phase Current","sq(3) * Phase Current","Phase Current / 3","Phase Current","Series connection to line."
808,8,"In balanced Delta, Line Voltage = ?","Phase Voltage","sq(3) * Phase Voltage","0","Phase Voltage","Parallel connection."
809,8,"In balanced Delta, Line Current = ?","sq(3) * Phase Current","Phase Current","Phase Current / sq(3)","sq(3) * Phase Current","Il lags Ip by 30."
810,8,"Neutral current in balanced Y system:","Zero","Max","Line Current","Zero","Phasors sum to 0."
811,8,"Total power in balanced 3-phase (Line values):","sq(3) Vl Il cos(theta)","3 Vl Il cos(theta)","Vl Il","sq(3) Vl Il cos(theta)","Standard formula."
812,8,"Total power in balanced 3-phase (Phase values):","3 Vp Ip cos(theta)","sq(3) Vp Ip","Vp Ip","3 Vp Ip cos(theta)","Sum of 3 phases."
813,8,"Two-Wattmeter method measures:","Total 3-phase power","Reactive power only","Line voltage","Total 3-phase power","Valid for balanced/unbalanced 3-wire."
814,8,"One wattmeter reads 0 if PF is:","0.5","1","0","0.5","60 degree phase shift."
815,8,"Wattmeters read equal if PF is:","1 (Unity)","0","0.5","1 (Unity)","Resistive load."
816,8,"Advantages of 3-phase:","Constant power, less copper","Simpler to wire","Lower voltage","Constant power, less copper","Efficient transmission."
817,8,"Instantaneous power in balanced 3-phase is:","Constant (DC like)","Pulsating","Zero","Constant (DC like)","No vibration in motors."
818,8,"Phase voltage implies voltage between:","Line and Neutral","Line and Line","Line and Ground","Line and Neutral","In Y-system."
819,8,"Line voltage implies voltage between:","Line and Line","Line and Neutral","Ground","Line and Line","Standard spec."
820,8,"In a balanced 3-phase system, the sum of instantaneous voltages is:","Zero","Maximum","Infinite","Zero","Phasor sum is 0."
821,8,"The Neutral point in a Star (Y) connection is:","Common point of 3 windings","Line connection","Floating","Common point of 3 windings","Vector sum point."
822,8,"Grounding (Earthing) is primarily used for:","Safety and Protection","Voltage boosting","Current blocking","Safety and Protection","Prevents shock/fire."
823,8,"Single phase from 3-phase is obtained via:","Line to Neutral","3 lines combined","Rectifier","Line to Neutral","V_ln."
824,8,"Alternator rotor is:","Electro-magnet","Resistor","Capacitor","Electro-magnet","Field winding."
825,8,"Stator carries:","Armature windings (AC)","DC field","Commutator","Armature windings (AC)","Stationary coils."
826,8,"Frequency depends on:","Speed and Poles","Voltage","Current","Speed and Poles","f = P*N/120."
827,8,"Unbalanced load causes:","Neutral current","Zero sequence current","Both A and B","Both A and B","Asymmetry."
828,8,"Delta connection has no:","Neutral point","Line current","Power","Neutral point","Loop."
829,8,"Y-Delta transform is also:","T-Pi transform","Star-Mesh","Both","Both","Equivalence."
830,8,"Zigzag transformer gives:","Grounding reference","Voltage boost","DC","Grounding reference","Earthing transformer."
831,8,"Third harmonics in 3-phase cancel in:","Delta connection lines","Y connection phases","None","Delta connection lines","Circulate in Delta."
832,8,"Synchronous motor speed:","Constant","Variable","Zero","Constant","Locked to freq."
833,8,"Induction motor slip:","Difference between sync and rotor speed","Efficiency","Friction","Difference between sync and rotor speed","Normally 2-5%."
834,8,"Power factor improvement capacitor is connected in:","Parallel (Shunt)","Series","Bridge","Parallel (Shunt)","Supplies VARs locally."
835,8,"V-curve of synchronous motor plots:","Armature current vs Field current","Speed vs Torque","V vs I","Armature current vs Field current","Min current at Unity PF."
836,8,"Per-unit system normalizes values to:","Base value","100","Grid voltage","Base value","Simplifies calcs."
837,8,"Fault analysis usually assumes:","Symmetrical components","DC analysis","Steady state","Symmetrical components","For unbalanced faults."
838,8,"Line-to-Ground fault is:","Most common","Rarest","Most severe","Most common","70-80% of faults."
839,8,"3-phase Short circuit is:","Most severe (usually)","Most common","Zero current","Most severe (usually)","Highest magnitude."
840,8,"Busbar is:","Common connection point","Resistor","Insulator","Common connection point","Node."
841,8,"Surge impedance loading (SIL) is:","Natural power limit of line","Max thermal limit","Min power","Natural power limit of line","V^2 / Z_surge."
842,8,"Infinite bus has:","Constant V and f","Infinite R","Zero Power","Constant V and f","Ideal grid."
843,8,"Relays allow:","Control of high power with low power","Speed control","Amplification","Control of high power with low power","Switching."
844,8,"CT stands for:","Current Transformer","Center Tap","Control Timer","Current Transformer","Instrument transformer."
845,8,"PT stands for:","Potential Transformer","Power Timer","Phase Tester","Potential Transformer","Steps down voltage."
846,8,"Isolator is operated:","Off-load","On-load","During fault","Off-load","No arc chute."
847,8,"Circuit Breaker is operated:","On-load/Fault","Off-load only","Never","On-load/Fault","Can break arc."
848,8,"Fuse provides protection against:","Overcurrent/Short circuit","Undervoltage","Frequency shift","Overcurrent/Short circuit","Melts."
849,8,"Grid synchronization requires matching:","Voltage, Freq, Phase sequence, Phase angle","Voltage only","Power only","Voltage, Freq, Phase sequence, Phase angle","All must match."
850,8,"Transmission voltages are high to:","Reduce I (Current) and I^2R loss","Increase current","Look cool","Reduce I (Current) and I^2R loss","Efficiency."
`;
